export * from './announcement.service';
export * from './fitness-class-template.service';
export * from './fitness-class-type.service';
export * from './fitness-class.service';
export * from './instructor.service';
export * from './location.service';
export * from './manage-attendees.service';
export * from './registration.service';
export * from './user.service';